# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: kartoza/postgis
    restart: always
    ports:
      
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1qazXSW@
      POSTGRES_USER: address
      POSTGRES_DB: address
